sudo: false

language: node_js
node_js:
  - "10"
  - "12"

env:
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=11

before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
